# Generated by Django 5.0.3 on 2024-04-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.AddField(
            model_name='donation',
            name='potential_donor',
            field=models.BooleanField(default=False),
        ),
    ]
